# This file was generated by GoReleaser. DO NOT EDIT.
cask "cascade" do
  name "cascade"
  desc "cascade workflow automation CLI for Git worktrees, Tmux, and Obsidian integration"
  homepage "https://github.com/unrss/cascade"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cascade"

  on_macos do
    on_intel do
      url "https://github.com/unrss/cascade/releases/download/v#{version}/cascade_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/unrss/cascade/"
      sha256 "3bfec6e9f28b375ce717f4e14e7aabc54f55927ce0a37905c1df92aed55f7dd0"
    end
    on_arm do
      url "https://github.com/unrss/cascade/releases/download/v#{version}/cascade_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/unrss/cascade/"
      sha256 "e152165efafeceff6da24c0f3c148db58eb7bc1e1f0d95b4f51c3aa2934e4496"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/unrss/cascade/releases/download/v#{version}/cascade_#{version}_linux_amd64.tar.gz",
        verified: "github.com/unrss/cascade/"
      sha256 "ea4517f1fcb7f43e0a482513a08b65ba974bc2a0832087c7428f1ad3f71d0def"
    end
    on_arm do
      url "https://github.com/unrss/cascade/releases/download/v#{version}/cascade_#{version}_linux_arm64.tar.gz",
        verified: "github.com/unrss/cascade/"
      sha256 "bdd7f4acf840efb764241ce877d6eb1b60825d3bfc35555709c1c168548a35ac"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cascade"]
    end
  end

  # No zap stanza required
end
